version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: slugdb
      POSTGRES_USER: katya
      POSTGRES_PASSWORD: katya
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgresql-data: