// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_get_user_slug is a generated GoMock package.
package mock_get_user_slug

import (
	context "context"
	reflect "reflect"
	time "time"

	users "github.com/frutonanny/slug-service/internal/repositories/users"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockusersRepo is a mock of usersRepo interface.
type MockusersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockusersRepoMockRecorder
}

// MockusersRepoMockRecorder is the mock recorder for MockusersRepo.
type MockusersRepoMockRecorder struct {
	mock *MockusersRepo
}

// NewMockusersRepo creates a new mock instance.
func NewMockusersRepo(ctrl *gomock.Controller) *MockusersRepo {
	mock := &MockusersRepo{ctrl: ctrl}
	mock.recorder = &MockusersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockusersRepo) EXPECT() *MockusersRepoMockRecorder {
	return m.recorder
}

// DeleteUserSlug mocks base method.
func (m *MockusersRepo) DeleteUserSlug(ctx context.Context, user uuid.UUID, slugID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSlug", ctx, user, slugID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSlug indicates an expected call of DeleteUserSlug.
func (mr *MockusersRepoMockRecorder) DeleteUserSlug(ctx, user, slugID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSlug", reflect.TypeOf((*MockusersRepo)(nil).DeleteUserSlug), ctx, user, slugID)
}

// GetUserSlugs mocks base method.
func (m *MockusersRepo) GetUserSlugs(ctx context.Context, userID uuid.UUID) ([]users.Slug, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSlugs", ctx, userID)
	ret0, _ := ret[0].([]users.Slug)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSlugs indicates an expected call of GetUserSlugs.
func (mr *MockusersRepoMockRecorder) GetUserSlugs(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSlugs", reflect.TypeOf((*MockusersRepo)(nil).GetUserSlugs), ctx, userID)
}

// MockeventsRepo is a mock of eventsRepo interface.
type MockeventsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockeventsRepoMockRecorder
}

// MockeventsRepoMockRecorder is the mock recorder for MockeventsRepo.
type MockeventsRepoMockRecorder struct {
	mock *MockeventsRepo
}

// NewMockeventsRepo creates a new mock instance.
func NewMockeventsRepo(ctrl *gomock.Controller) *MockeventsRepo {
	mock := &MockeventsRepo{ctrl: ctrl}
	mock.recorder = &MockeventsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventsRepo) EXPECT() *MockeventsRepoMockRecorder {
	return m.recorder
}

// AddEventWithCreatedAt mocks base method.
func (m *MockeventsRepo) AddEventWithCreatedAt(ctx context.Context, userID uuid.UUID, slugID int64, event string, createdAt time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventWithCreatedAt", ctx, userID, slugID, event, createdAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddEventWithCreatedAt indicates an expected call of AddEventWithCreatedAt.
func (mr *MockeventsRepoMockRecorder) AddEventWithCreatedAt(ctx, userID, slugID, event, createdAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventWithCreatedAt", reflect.TypeOf((*MockeventsRepo)(nil).AddEventWithCreatedAt), ctx, userID, slugID, event, createdAt)
}

// Mocktransactor is a mock of transactor interface.
type Mocktransactor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactorMockRecorder
}

// MocktransactorMockRecorder is the mock recorder for Mocktransactor.
type MocktransactorMockRecorder struct {
	mock *Mocktransactor
}

// NewMocktransactor creates a new mock instance.
func NewMocktransactor(ctrl *gomock.Controller) *Mocktransactor {
	mock := &Mocktransactor{ctrl: ctrl}
	mock.recorder = &MocktransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactor) EXPECT() *MocktransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *Mocktransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MocktransactorMockRecorder) RunInTx(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*Mocktransactor)(nil).RunInTx), ctx, f)
}
