POST localhost:8081/v1/createSlug
Content-Type: application/json

{
  "name": "AVITO_VOICE_MESSAGES"
}

### С опциями.
POST localhost:8081/v1/createSlug
Content-Type: application/json

{
  "name": "AVITO_PERFORMANCE_VAS"
}

###
POST localhost:8081/v1/createSlug
Content-Type: application/json

{
  "name": "AVITO_DISCOUNT_30"
}