POST localhost:8081/v1/modifyUserSlugs
Content-Type: application/json

{
  "userID": "53aa35c8-e659-44b2-882f-f6056e443c99",
  "add": [
    {
      "name": "AVITO_VOICE_MESSAGES"
    },
    {
      "name": "AVITO_PERFORMANCE_VAS"
    },
    {
      "name": "AVITO_DISCOUNT_30"
    }
  ]
}
