// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_delete_slug is a generated GoMock package.
package mock_delete_slug

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockslugRepo is a mock of slugRepo interface.
type MockslugRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslugRepoMockRecorder
}

// MockslugRepoMockRecorder is the mock recorder for MockslugRepo.
type MockslugRepoMockRecorder struct {
	mock *MockslugRepo
}

// NewMockslugRepo creates a new mock instance.
func NewMockslugRepo(ctrl *gomock.Controller) *MockslugRepo {
	mock := &MockslugRepo{ctrl: ctrl}
	mock.recorder = &MockslugRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslugRepo) EXPECT() *MockslugRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockslugRepo) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockslugRepoMockRecorder) Delete(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockslugRepo)(nil).Delete), ctx, name)
}
